spring:
  application:
    name: provider-demo
server:
  port: 8081

dubbo:
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20881
  application:
    register-mode: instance
  scan:
    base-packages: com.example.provider.rpcservice










